from typing import Literal
from pydantic import BaseModel, ConfigDict, Field
from pydantic import AwareDatetime


class MessageIn(BaseModel):
    """
    A single message turn in the Canonical Message Format (CMF).
    Represents one user or assistant message, verbatim.
    The client (Claude/ChatGPT/Gemini adapter) is responsible
    for generating the messageId (UUID v4).
    """

    model_config = ConfigDict(
        str_strip_whitespace=False,   # never silently strip content
        extra="forbid",               # reject unknown fields
    )

    messageId: str = Field(
        ...,
        description="UUID v4 generated by the client. Used for idempotent writes.",
        min_length=1,
    )
    role: Literal["user", "assistant"] = Field(
        ...,
        description="Who produced this message.",
    )
    content: str = Field(
        ...,
        description="Full verbatim message content. Never truncated or modified.",
        min_length=1,
    )
    timestamp: AwareDatetime = Field(
        ...,
        description="ISO 8601 timestamp with timezone. When this message was produced.",
    )
    tokenCount: int = Field(
        ...,
        ge=0,
        description="Token count of this message as reported by the originating LLM.",
    )
