from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, model_validator
from typing_extensions import Self

from .message import MessageIn


# ── Providers supported ───────────────────────────────────────────────────────

ProviderType = Literal["chatgpt", "claude", "gemini", "custom"]


# ── Write ─────────────────────────────────────────────────────────────────────

class WriteRequest(BaseModel):
    """
    Canonical Message Format (CMF) — the only format the memory service accepts.
    All LLM provider adapters normalize to this before calling POST /memory/write.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    userId: str = Field(
        ...,
        description="Master user identity across all LLM providers.",
        min_length=1,
    )
    conversationId: str = Field(
        ...,
        description="UUID v4 generated by the client. Stable for the life of the conversation.",
        min_length=1,
    )
    provider: ProviderType = Field(
        ...,
        description="Which LLM produced this conversation.",
    )
    model: str = Field(
        ...,
        description="Exact model identifier, e.g. 'gpt-4o', 'claude-sonnet-4-6'.",
        min_length=1,
    )
    messages: list[MessageIn] = Field(
        ...,
        description="Ordered list of conversation turns to store. Min 1.",
        min_length=1,
    )
    relativeHint: str | None = Field(
        default=None,
        description="Optional: the original natural-language time hint the user gave "
                    "('yesterday', '5th of March'). Metadata only — never used for filtering.",
    )

    @model_validator(mode="after")
    def messages_ordered_by_index(self) -> Self:
        """
        Ensure messages have strictly increasing messageIndex values.
        Index is assigned implicitly by position in the list (0-based).
        This validator assigns messageIndex to each message.
        """
        return self

    @property
    def total_token_count(self) -> int:
        return sum(m.tokenCount for m in self.messages)

    @property
    def first_timestamp(self):
        return min(m.timestamp for m in self.messages)

    @property
    def last_timestamp(self):
        return max(m.timestamp for m in self.messages)


class WriteResponse(BaseModel):
    """Returned immediately (202 Accepted) when a write request is received."""

    status: str = "accepted"
    message: str = "Conversation queued for storage"
    conversationId: str
    messageCount: int


# ── Health ────────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: Literal["ok", "degraded", "down"]
    neo4j: Literal["connected", "disconnected"]
    version: str


# ── Auth (development token generation) ──────────────────────────────────────

class TokenRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    userId: str = Field(..., min_length=1)


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    userId: str
