from datetime import datetime
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, model_validator
from typing_extensions import Self

from .message import MessageIn


# ── Providers supported ───────────────────────────────────────────────────────

ProviderType = Literal["chatgpt", "claude", "gemini", "grok", "copilot", "custom"]


# ── Write ─────────────────────────────────────────────────────────────────────

class WriteRequest(BaseModel):
    """
    Canonical Message Format (CMF) — the only format the memory service accepts.
    All LLM provider adapters normalize to this before calling POST /memory/write.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    userId: str = Field(
        ...,
        description="Master user identity across all LLM providers.",
        min_length=1,
    )
    conversationId: str = Field(
        ...,
        description="UUID v4 generated by the client. Stable for the life of the conversation.",
        min_length=1,
    )
    provider: ProviderType = Field(
        ...,
        description="Which LLM produced this conversation.",
    )
    model: str = Field(
        ...,
        description="Exact model identifier, e.g. 'gpt-4o', 'claude-sonnet-4-6'.",
        min_length=1,
    )
    messages: list[MessageIn] = Field(
        ...,
        description="Ordered list of conversation turns to store. Min 1.",
        min_length=1,
    )
    relativeHint: str | None = Field(
        default=None,
        description="Optional: the original natural-language time hint the user gave "
                    "('yesterday', '5th of March'). Metadata only — never used for filtering.",
    )

    @model_validator(mode="after")
    def messages_ordered_by_index(self) -> Self:
        """
        Ensure messages have strictly increasing messageIndex values.
        Index is assigned implicitly by position in the list (0-based).
        This validator assigns messageIndex to each message.
        """
        return self

    @property
    def total_token_count(self) -> int:
        return sum(m.tokenCount for m in self.messages)

    @property
    def first_timestamp(self):
        return min(m.timestamp for m in self.messages)

    @property
    def last_timestamp(self):
        return max(m.timestamp for m in self.messages)


class WriteResponse(BaseModel):
    """Returned immediately (202 Accepted) when a write request is received."""

    status: str = "accepted"
    message: str = "Conversation queued for storage"
    conversationId: str
    messageCount: int


# ── Health ────────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: Literal["ok", "degraded", "down"]
    neo4j: Literal["connected", "disconnected"]
    version: str


# ── Query ─────────────────────────────────────────────────────────────────────

class QueryRequest(BaseModel):
    """
    Semantic memory query request.

    Date filtering:
      Use `date` for a single day, OR `dateFrom`/`dateTo` for a range.
      They are mutually exclusive.  All values must be YYYY-MM-DD strings.
      The LLM client is responsible for resolving relative expressions
      ("yesterday", "last week") to absolute dates before calling this API.
    """

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    userId: str = Field(..., min_length=1)
    query: str = Field(..., min_length=1, max_length=2000)
    topK: int = Field(default=5, ge=1, le=20)
    tokenBudget: int = Field(
        default=4000, ge=100, le=16000,
        description="Maximum total tokens in the assembled response.",
    )
    providers: list[ProviderType] | None = Field(
        default=None,
        description="Restrict search to specific providers. None = all providers.",
    )

    # Date filters — mutually exclusive
    date: str | None = Field(
        default=None,
        description="YYYY-MM-DD — search only conversations from this exact day.",
    )
    dateFrom: str | None = Field(
        default=None,
        description="YYYY-MM-DD — search conversations starting from this date (inclusive).",
    )
    dateTo: str | None = Field(
        default=None,
        description="YYYY-MM-DD — search conversations up to this date (inclusive).",
    )
    relativeHint: str | None = Field(
        default=None,
        description="The original natural-language hint ('last Tuesday'). Metadata only.",
    )

    @model_validator(mode="after")
    def validate_date_fields(self) -> Self:
        has_exact = self.date is not None
        has_range = self.dateFrom is not None or self.dateTo is not None

        if has_exact and has_range:
            raise ValueError("Use either `date` or `dateFrom`/`dateTo`, not both.")

        if self.dateTo is not None and self.dateFrom is None:
            raise ValueError("`dateTo` requires `dateFrom`.")

        for field_name, value in [
            ("date", self.date),
            ("dateFrom", self.dateFrom),
            ("dateTo", self.dateTo),
        ]:
            if value is not None:
                try:
                    datetime.strptime(value, "%Y-%m-%d")
                except ValueError:
                    raise ValueError(f"`{field_name}` must be YYYY-MM-DD format.")

        return self

    @property
    def has_date_filter(self) -> bool:
        return self.date is not None or self.dateFrom is not None

    @property
    def effective_date_from(self) -> str | None:
        """Resolved start of date range (works for both `date` and `dateFrom`)."""
        return self.date or self.dateFrom

    @property
    def effective_date_to(self) -> str | None:
        """Resolved end of date range (works for both `date` and `dateTo`)."""
        return self.date or self.dateTo


class MessageResult(BaseModel):
    """A single verbatim message turn in a query result."""
    messageId: str
    role: str
    content: str
    timestamp: str
    tokenCount: int


class ConversationResult(BaseModel):
    """A group of verbatim messages from one conversation, with relevance score."""
    score: float
    conversationId: str
    provider: str
    model: str
    conversationDate: str           # YYYY-MM-DD
    conversationStartedAt: str      # ISO-8601 full timestamp
    messages: list[MessageResult]


class QueryResponse(BaseModel):
    """Full response from POST /memory/query."""
    results: list[ConversationResult]
    totalResults: int
    tokenCount: int                 # total tokens in assembled results
    queryLatencyMs: float
    dateFilterApplied: bool
    searchMode: Literal["vector", "fulltext", "empty"]


# ── Phase 3: Read / List / Delete models ─────────────────────────────────────

class ConversationSummary(BaseModel):
    """One row in the conversation list response."""
    conversationId: str
    provider: str
    model: str
    messageCount: int
    totalTokens: int
    segmentCount: int
    startedAt: str      # ISO-8601
    endedAt: str        # ISO-8601
    isComplete: bool


class ListConversationsResponse(BaseModel):
    """Paginated list of a user's stored conversations."""
    conversations: list[ConversationSummary]
    total: int
    limit: int
    offset: int


class ConversationReadResponse(BaseModel):
    """
    Full verbatim conversation — all messages in chronological order.
    Returned by GET /memory/conversation/{conversationId}.
    """
    conversationId: str
    userId: str
    provider: str
    model: str
    messageCount: int
    totalTokens: int
    startedAt: str
    endedAt: str
    messages: list[MessageResult]


class DeleteResponse(BaseModel):
    """Confirmation returned by all DELETE endpoints."""
    status: str = "deleted"
    message: str
    deletedId: str          # conversationId or userId, depending on endpoint
    nodesDeleted: int       # total Neo4j nodes removed


# ── Auth (development token generation) ──────────────────────────────────────

class TokenRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    userId: str = Field(..., min_length=1)


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    userId: str


# ── Phase 5: ChatGPT Custom GPT Action models ─────────────────────────────────

class ChatGPTMessage(BaseModel):
    """
    A single message as sent by a ChatGPT Custom GPT Action.
    Accepts role + content only — no pre-generated IDs or timestamps required.
    system/tool roles are silently filtered out before storage.
    """

    model_config = ConfigDict(extra="ignore")   # GPT may send extra fields; ignore them

    role: str = Field(..., description="Message role: user, assistant, system, tool.")
    content: str = Field(..., min_length=0, description="Verbatim message content.")


class ChatGPTWriteRequest(BaseModel):
    """
    Simplified write payload accepted by POST /chatgpt/write.
    Designed to be constructable by a Custom GPT Action without any
    pre-processing — the server normalises internally via the chatgpt adapter.
    """

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    userId: str = Field(
        ...,
        min_length=1,
        description="Master userId — must match the Bearer token sub claim.",
    )
    conversationId: str | None = Field(
        default=None,
        min_length=1,
        description=(
            "Stable UUID v4 for this conversation. If omitted the server generates one. "
            "Providing the same conversationId on repeated writes is idempotent."
        ),
    )
    model: str = Field(
        default="gpt-4o",
        min_length=1,
        description="OpenAI model identifier, e.g. 'gpt-4o', 'gpt-4-turbo'.",
    )
    messages: list[ChatGPTMessage] = Field(
        ...,
        min_length=1,
        description="Ordered conversation turns. system/tool roles are filtered out.",
    )
    title: str | None = Field(
        default=None,
        description="Optional conversation title (metadata only, not stored in graph).",
    )


class ChatGPTWriteResponse(BaseModel):
    """Returned immediately (202 Accepted) when a ChatGPT write is accepted."""

    status: str = "accepted"
    message: str = "Conversation queued for storage"
    conversationId: str       # echoed back (useful when server generated it)
    messageCount: int         # number of user/assistant turns stored (after filtering)
    provider: str = "chatgpt"


# ── Phase 5: API Key issuance (third-party integrations) ─────────────────────

class ApiKeyRequest(BaseModel):
    """Request body for POST /auth/apikey."""

    model_config = ConfigDict(extra="forbid")

    userId: str = Field(
        ...,
        min_length=1,
        description="The userId this API key will authenticate as.",
    )


class ApiKeyResponse(BaseModel):
    """
    Long-lived API key response.
    The api_key value is a signed JWT valid for 1 year.
    Store it securely — it authenticates as userId for all memory operations.
    """

    api_key: str
    token_type: str = "bearer"
    userId: str
    expires_at: str           # ISO-8601 timestamp when the key expires


# ── Phase 7: Token revocation ───────────────────────────────────────────────

class RevokeTokenRequest(BaseModel):
    """Request body for POST /auth/revoke."""

    model_config = ConfigDict(extra="forbid")

    token: str = Field(
        ...,
        min_length=1,
        description="The JWT token to revoke. Must belong to the authenticated user.",
    )


class RevokeTokenResponse(BaseModel):
    """Confirmation that a token has been revoked."""

    status: str = "revoked"
    message: str
    jti: str
